"""
RDF-StarBase Storage Layer.

High-performance columnar storage with dictionary-encoded terms
and predicate-partitioned facts.
"""

from rdf_starbase.storage.terms import (
    TermKind,
    TermId,
    TermDict,
    Term,
)
from rdf_starbase.storage.quoted_triples import QtDict, QtId
from rdf_starbase.storage.facts import FactStore, FactFlags, DEFAULT_GRAPH_ID
from rdf_starbase.storage.lsm import LSMStorage, PartitionStats
from rdf_starbase.storage.executor import StorageExecutor, ExpansionPatterns
from rdf_starbase.storage.reasoner import RDFSReasoner, ReasoningStats
from rdf_starbase.storage.persistence import (
    StoragePersistence,
    save_storage,
    load_storage,
)
from rdf_starbase.storage.duckdb import (
    DuckDBInterface,
    SQLQueryResult,
    TableInfo,
    create_sql_interface,
    check_duckdb_available,
)
from rdf_starbase.storage.wal import (
    WriteAheadLog,
    WALEntry,
    WALEntryType,
    InsertPayload,
    DeletePayload,
    CheckpointState,
)
from rdf_starbase.storage.transactions import (
    Transaction,
    TransactionManager,
    TransactionState,
    IsolationLevel,
)
from rdf_starbase.storage.query_context import (
    QueryContext,
    QueryState,
    QueryStats,
    CancellationToken,
    QueryCancelledException,
    QueryTimeoutException,
    ExplainPlan,
    QueryExecutionManager,
    execute_with_timeout,
    query_timeout,
)
from rdf_starbase.storage.connection_pool import (
    ConnectionPool,
    SharedExecutorPool,
    PooledConnection,
    PoolStats,
    ConnectionMode,
    PoolExhaustedError,
)
from rdf_starbase.storage.partitioning import (
    PredicatePartitioner,
    PartitionInfo,
    PartitionStats as PredicatePartitionStats,
)
from rdf_starbase.storage.indexing import (
    SortedIndex,
    IndexManager,
    IndexStats,
    IndexEntry,
    indexed_filter,
    estimate_selectivity,
    should_use_index,
)
from rdf_starbase.storage.memory_budget import (
    MemoryBudget,
    MemoryGuard,
    MemoryStats,
    MemoryPressure,
    BudgetedStore,
    estimate_size,
    configure_budget,
    get_budget,
    track,
    untrack,
    enforce,
)
from rdf_starbase.storage.backup import (
    BackupManager,
    BackupManifest,
    BackupProgress,
    BackupState,
    BackupFormat,
    RestoreOptions,
    snapshot_repository,
    restore_repository,
)
from rdf_starbase.storage.staging import (
    StagingManager,
    StagingSession,
    StagingManifest,
    StagingState,
    StagedTriple,
    ImportPreview,
    ValidationResult,
    stage_import,
    preview_import,
)
from rdf_starbase.storage.queries import (
    SavedQueryManager,
    SavedQuery,
    QueryCollection,
    QueryParameter,
    QueryExecution,
    QueryType,
    detect_query_type,
    extract_parameters,
    save_query,
    load_query,
)
from rdf_starbase.storage.observability import (
    MetricType,
    MetricValue,
    Metric,
    MetricsCollector,
    Timer,
    SystemStats,
    StoreStats,
    QueryStats as ObservabilityQueryStats,
    HealthStatus,
    HealthCheck,
    ObservabilityManager,
    get_observability,
    record_request,
    record_query,
)
from rdf_starbase.storage.repo_config import (
    ReasoningLevel,
    MemoryConfig,
    QueryConfig,
    ReasoningConfig,
    StorageConfig,
    RepositoryConfig,
    MigrationStep,
    SchemaMigrator,
    ConfigValidator,
    ConfigManager,
    SchemaVersionError,
    ConfigValidationError,
    CURRENT_SCHEMA_VERSION,
    get_schema_version,
    create_default_config,
)
from rdf_starbase.storage.import_jobs import (
    ImportStatus,
    ImportErrorSeverity,
    ImportError as ImportJobError,
    ImportProgress,
    ImportJob,
    ImportJobTracker,
    ImportUndoManager,
    create_import_tracker,
    create_undo_manager,
)
from rdf_starbase.storage.graph_explorer import (
    GraphStatistics,
    GraphMetadata,
    GraphInfo,
    GraphExplorer,
    explore_graphs,
)
from rdf_starbase.storage.query_tools import (
    SlowQueryEntry,
    SlowQueryLog,
    QueryTimer,
    ExportFormat,
    ExportOptions,
    ResultExporter,
    CursorPage,
    CursorPaginator,
    create_slow_log,
    export_results,
    paginate_results,
)
from rdf_starbase.storage.auth import (
    Role,
    Operation,
    READ_OPERATIONS,
    WRITE_OPERATIONS,
    ADMIN_OPERATIONS,
    APIKey,
    ScopedToken,
    RateLimitState,
    RateLimitExceeded,
    AuthorizationError,
    APIKeyManager,
    AuthContext,
    PermissionPolicy,
    create_key_manager,
    require_auth,
)
from rdf_starbase.storage.audit import (
    AuditAction,
    AuditSeverity,
    AuditEntry,
    AuditLog,
    LineageNode,
    LineageEdge,
    DataLineage,
    SourceHealth,
    SourceHealthMonitor,
    create_audit_log,
    create_lineage_tracker,
    create_health_monitor,
)
from rdf_starbase.storage.trust import (
    ConflictStrategy,
    DecayFunction,
    TrustPolicy,
    TrustAssertion,
    Conflict,
    TrustPolicyManager,
    ConflictResolver,
    TrustInheritance,
    TrustScore,
    TrustScorer,
    create_policy_manager,
    create_conflict_resolver,
    create_trust_scorer,
    create_trust_inheritance,
)
from rdf_starbase.storage.federation import (
    EndpointStatus,
    SyncDirection,
    SyncStrategy,
    QueryPushdownType,
    RemoteEndpoint,
    ServiceCall,
    FederatedResult,
    SyncState,
    SyncOperation,
    EndpointRegistry,
    ServiceClauseParser,
    FederatedQueryExecutor,
    CrossInstanceSync,
    DistributedQueryPlanner,
    create_federation_executor,
    create_sync_manager,
)
from rdf_starbase.storage.tenancy import (
    TenantStatus,
    QuotaType,
    IsolationLevel,
    ResourceQuota,
    TenantConfig,
    QuotaExceededError,
    TenantNotFoundError,
    TenantSuspendedError,
    TenantManager,
    TenantContext,
    UsageTracker,
    create_tenant_manager,
    get_current_tenant,
)
from rdf_starbase.storage.ops import (
    HealthStatus as OpsHealthStatus,
    CheckType,
    HealthCheckResult,
    HealthReport,
    HealthChecker,
    MetricType as OpsMetricType,
    MetricDefinition,
    MetricsCollector as OpsMetricsCollector,
    SpanContext,
    Span,
    Tracer,
    OperationsManager,
    create_health_checker,
    create_metrics_collector,
    create_tracer,
    create_operations_manager,
)

__all__ = [
    "TermKind",
    "TermId",
    "TermDict",
    "Term",
    "QtDict",
    "QtId",
    "FactStore",
    "FactFlags",
    "DEFAULT_GRAPH_ID",
    "LSMStorage",
    "PartitionStats",
    "StorageExecutor",
    "ExpansionPatterns",
    "RDFSReasoner",
    "ReasoningStats",
    "StoragePersistence",
    "save_storage",
    "load_storage",
    # DuckDB SQL Interface
    "DuckDBInterface",
    "SQLQueryResult",
    "TableInfo",
    "create_sql_interface",
    "check_duckdb_available",
    # Write-Ahead Log
    "WriteAheadLog",
    "WALEntry",
    "WALEntryType",
    "InsertPayload",
    "DeletePayload",
    "CheckpointState",
    # Transactions
    "Transaction",
    "TransactionManager",
    "TransactionState",
    "IsolationLevel",
    # Query Context & Timeout
    "QueryContext",
    "QueryState",
    "QueryStats",
    "CancellationToken",
    "QueryCancelledException",
    "QueryTimeoutException",
    "ExplainPlan",
    "QueryExecutionManager",
    "execute_with_timeout",
    "query_timeout",
    # Connection Pooling
    "ConnectionPool",
    "SharedExecutorPool",
    "PooledConnection",
    "PoolStats",
    "ConnectionMode",
    "PoolExhaustedError",
    # Predicate Partitioning
    "PredicatePartitioner",
    "PartitionInfo",
    "PredicatePartitionStats",
    # Indexing
    "SortedIndex",
    "IndexManager",
    "IndexStats",
    "IndexEntry",
    "indexed_filter",
    "estimate_selectivity",
    "should_use_index",
    # Memory Budget
    "MemoryBudget",
    "MemoryGuard",
    "MemoryStats",
    "MemoryPressure",
    "BudgetedStore",
    "estimate_size",
    "configure_budget",
    "get_budget",
    "track",
    "untrack",
    "enforce",
    # Backup/Restore
    "BackupManager",
    "BackupManifest",
    "BackupProgress",
    "BackupState",
    "BackupFormat",
    "RestoreOptions",
    "snapshot_repository",
    "restore_repository",
    # Import Staging
    "StagingManager",
    "StagingSession",
    "StagingManifest",
    "StagingState",
    "StagedTriple",
    "ImportPreview",
    "ValidationResult",
    "stage_import",
    "preview_import",
    # Saved Queries
    "SavedQueryManager",
    "SavedQuery",
    "QueryCollection",
    "QueryParameter",
    "QueryExecution",
    "QueryType",
    "detect_query_type",
    "extract_parameters",
    "save_query",
    "load_query",
    # Observability
    "MetricType",
    "MetricValue",
    "Metric",
    "MetricsCollector",
    "Timer",
    "SystemStats",
    "StoreStats",
    "ObservabilityQueryStats",
    "HealthStatus",
    "HealthCheck",
    "ObservabilityManager",
    "get_observability",
    "record_request",
    "record_query",
    # Repository Configuration
    "ReasoningLevel",
    "MemoryConfig",
    "QueryConfig",
    "ReasoningConfig",
    "StorageConfig",
    "RepositoryConfig",
    "MigrationStep",
    "SchemaMigrator",
    "ConfigValidator",
    "ConfigManager",
    "SchemaVersionError",
    "ConfigValidationError",
    "CURRENT_SCHEMA_VERSION",
    "get_schema_version",
    "create_default_config",
    # Import Jobs
    "ImportStatus",
    "ImportErrorSeverity",
    "ImportJobError",
    "ImportProgress",
    "ImportJob",
    "ImportJobTracker",
    "ImportUndoManager",
    "create_import_tracker",
    "create_undo_manager",
    # Graph Explorer
    "GraphStatistics",
    "GraphMetadata",
    "GraphInfo",
    "GraphExplorer",
    "explore_graphs",
    # Query Tools
    "SlowQueryEntry",
    "SlowQueryLog",
    "QueryTimer",
    "ExportFormat",
    "ExportOptions",
    "ResultExporter",
    "CursorPage",
    "CursorPaginator",
    "create_slow_log",
    "export_results",
    "paginate_results",
    # Authentication & Authorization
    "Role",
    "Operation",
    "READ_OPERATIONS",
    "WRITE_OPERATIONS",
    "ADMIN_OPERATIONS",
    "APIKey",
    "ScopedToken",
    "RateLimitState",
    "RateLimitExceeded",
    "AuthorizationError",
    "APIKeyManager",
    "AuthContext",
    "PermissionPolicy",
    "create_key_manager",
    "require_auth",
    # Audit & Compliance
    "AuditAction",
    "AuditSeverity",
    "AuditEntry",
    "AuditLog",
    "LineageNode",
    "LineageEdge",
    "DataLineage",
    "SourceHealth",
    "SourceHealthMonitor",
    "create_audit_log",
    "create_lineage_tracker",
    "create_health_monitor",
    # Trust Scoring
    "ConflictStrategy",
    "DecayFunction",
    "TrustPolicy",
    "TrustAssertion",
    "Conflict",
    "TrustPolicyManager",
    "ConflictResolver",
    "TrustInheritance",
    "TrustScore",
    "TrustScorer",
    "create_policy_manager",
    "create_conflict_resolver",
    "create_trust_scorer",
    "create_trust_inheritance",
    # Federation
    "EndpointStatus",
    "SyncDirection",
    "SyncStrategy",
    "QueryPushdownType",
    "RemoteEndpoint",
    "ServiceCall",
    "FederatedResult",
    "SyncState",
    "SyncOperation",
    "EndpointRegistry",
    "ServiceClauseParser",
    "FederatedQueryExecutor",
    "CrossInstanceSync",
    "DistributedQueryPlanner",
    "create_federation_executor",
    "create_sync_manager",
    # Multi-tenancy
    "TenantStatus",
    "QuotaType",
    "IsolationLevel",
    "ResourceQuota",
    "TenantConfig",
    "QuotaExceededError",
    "TenantNotFoundError",
    "TenantSuspendedError",
    "TenantManager",
    "TenantContext",
    "UsageTracker",
    "create_tenant_manager",
    "get_current_tenant",
    # Enterprise Operations
    "OpsHealthStatus",
    "CheckType",
    "HealthCheckResult",
    "HealthReport",
    "HealthChecker",
    "OpsMetricType",
    "MetricDefinition",
    "OpsMetricsCollector",
    "SpanContext",
    "Span",
    "Tracer",
    "OperationsManager",
    "create_health_checker",
    "create_metrics_collector",
    "create_tracer",
    "create_operations_manager",
]
